use std::fmt::Write as _;

use super::sq;
use crate::Node;

pub(crate) fn generate(root: &Node) -> String {
    let bin = root.path.first().cloned().unwrap_or_default();
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# bash completion for {bin}, generated by hasami-complete\n_{}() {{",
        root.ident()
    );
    out.push_str("    local cur prev words cword\n");
    out.push_str("    if declare -F _init_completion >/dev/null 2>&1; then\n        _init_completion || return\n    else\n        COMPREPLY=(); cur=\"${COMP_WORDS[COMP_CWORD]}\"; prev=\"${COMP_WORDS[COMP_CWORD-1]}\"; words=(\"${COMP_WORDS[@]}\"); cword=$COMP_CWORD\n    fi\n");
    // Walk the typed words to find the deepest subcommand.
    out.push_str("    local cmd=\"root\" i\n    for ((i = 1; i < cword; i++)); do\n        case \"$cmd,${words[i]}\" in\n");
    emit_transitions(&mut out, root, "root");
    out.push_str("        esac\n    done\n");
    // Values for the previous option.
    out.push_str("    case \"$cmd,$prev\" in\n");
    emit_values(&mut out, root, "root");
    out.push_str("    esac\n");
    // Words at this level.
    out.push_str("    case \"$cmd\" in\n");
    emit_words(&mut out, root, "root");
    out.push_str(
        "    esac\n    COMPREPLY=($(compgen -W \"$opts\" -- \"$cur\"))\n    return 0\n}\n",
    );
    let _ = writeln!(out, "complete -F _{} {}", root.ident(), sq(&bin));
    out
}

fn emit_transitions(out: &mut String, node: &Node, state: &str) {
    for s in &node.subs {
        let name = s.path.last().cloned().unwrap_or_default();
        let next = s.ident();
        let _ = writeln!(out, "            {state},{name}) cmd={} ;;", sq(&next));
        emit_transitions(out, s, &next);
    }
}

fn emit_values(out: &mut String, node: &Node, state: &str) {
    for o in &node.opts {
        if !o.takes_value {
            continue;
        }
        let mut names = Vec::new();
        if let Some(c) = o.short {
            names.push(format!("-{c}"));
        }
        if let Some(l) = &o.long {
            names.push(format!("--{l}"));
        }
        for a in &o.aliases {
            names.push(format!("--{a}"));
        }
        let pats: Vec<String> = names.iter().map(|n| format!("{state},{n}")).collect();
        let values = if o.possible.is_empty() {
            "COMPREPLY=($(compgen -f -- \"$cur\")); return 0".to_owned()
        } else {
            format!(
                "COMPREPLY=($(compgen -W {} -- \"$cur\")); return 0",
                sq(&o.possible.join(" "))
            )
        };
        let _ = writeln!(out, "        {}) {values} ;;", pats.join("|"));
    }
    for s in &node.subs {
        emit_values(out, s, &s.ident());
    }
}

fn emit_words(out: &mut String, node: &Node, state: &str) {
    let _ = writeln!(
        out,
        "        {state}) opts={} ;;",
        sq(&node.words().join(" "))
    );
    for s in &node.subs {
        emit_words(out, s, &s.ident());
    }
}

pub(crate) fn dynamic(bin: &str) -> String {
    let ident: String = bin
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    format!(
        "# dynamic bash completion for {bin}, generated by hasami-complete\n\
_{ident}_dynamic() {{\n\
    local IFS=$'\\n'\n\
    COMPREPLY=($(_HASAMI_COMPLETE=bash _HASAMI_COMPLETE_INDEX=\"$COMP_CWORD\" _HASAMI_COMPLETE_WORDS=\"$(printf '%s\\x1f' \"${{COMP_WORDS[@]}}\")\" {bin}))\n\
}}\n\
complete -o default -F _{ident}_dynamic {bin}\n",
        bin = sq(bin),
    )
}
