use std::fmt::Write as _;

use super::sq;
use crate::Node;

pub(crate) fn generate(root: &Node) -> String {
    let bin = root.path.first().cloned().unwrap_or_default();
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# fish completion for {bin}, generated by hasami-complete"
    );
    emit(&mut out, root, &bin);
    out
}

fn condition(node: &Node) -> String {
    // Subcommand words after the binary name.
    let subs: Vec<&str> = node.path.iter().skip(1).map(String::as_str).collect();
    if subs.is_empty() {
        "__fish_use_subcommand".to_owned()
    } else {
        format!(
            "__fish_seen_subcommand_from {}",
            subs.last().copied().unwrap_or("")
        )
    }
}

fn emit(out: &mut String, node: &Node, bin: &str) {
    let cond = condition(node);
    for o in &node.opts {
        let mut line = format!("complete -c {} -n {}", sq(bin), sq(&cond));
        if let Some(c) = o.short {
            let _ = write!(line, " -s {c}");
        }
        if let Some(l) = &o.long {
            let _ = write!(line, " -l {l}");
        }
        for a in &o.aliases {
            let _ = write!(line, " -l {a}");
        }
        if !o.help.is_empty() {
            let _ = write!(line, " -d {}", sq(&o.help));
        }
        if o.takes_value {
            if o.possible.is_empty() {
                line.push_str(" -r -F");
            } else {
                let _ = write!(line, " -r -f -a {}", sq(&o.possible.join(" ")));
            }
        }
        out.push_str(&line);
        out.push('\n');
    }
    if node.help_flag {
        let _ = writeln!(
            out,
            "complete -c {} -n {} -s h -l help -d 'Print help'",
            sq(bin),
            sq(&cond)
        );
    }
    if node.version_flag {
        let _ = writeln!(
            out,
            "complete -c {} -n {} -s V -l version -d 'Print version'",
            sq(bin),
            sq(&cond)
        );
    }
    for s in &node.subs {
        let name = s.path.last().cloned().unwrap_or_default();
        let _ = writeln!(
            out,
            "complete -c {} -n {} -f -a {} -d {}",
            sq(bin),
            sq(&cond),
            sq(&name),
            sq(&s.about)
        );
    }
    for s in &node.subs {
        emit(out, s, bin);
    }
}

pub(crate) fn dynamic(bin: &str) -> String {
    format!(
        "# dynamic fish completion for {bin}, generated by hasami-complete\n\
complete -c {q} -f -a '(set -lx _HASAMI_COMPLETE fish; set -lx _HASAMI_COMPLETE_WORDS (string join \\x1f (commandline -op)); set -lx _HASAMI_COMPLETE_INDEX (math (count (commandline -opc)) - 1); {q})'\n",
        q = sq(bin),
    )
}
