use std::fmt::Write as _;

use crate::Node;

fn nq(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

pub(crate) fn generate(root: &Node) -> String {
    let bin = root.path.first().cloned().unwrap_or_default();
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# nushell completion for {bin}, generated by hasami-complete\nmodule completions {{"
    );
    emit(&mut out, root);
    out.push_str("}\n\nuse completions *\n");
    out
}

fn emit(out: &mut String, node: &Node) {
    for o in &node.opts {
        if !o.possible.is_empty() {
            let items: Vec<String> = o.possible.iter().map(|v| nq(v)).collect();
            let _ = writeln!(
                out,
                "  def {} [] {{ [{}] }}",
                completer_name(node, o),
                items.join(" ")
            );
        }
    }
    if !node.about.is_empty() {
        let _ = writeln!(out, "  # {}", node.about);
    }
    let _ = writeln!(out, "  export extern {} [", nq(&node.path.join(" ")));
    for p in &node.positionals {
        let _ = writeln!(
            out,
            "    {}?: string # {}",
            p.value_name.to_lowercase(),
            p.help
        );
    }
    for o in &node.opts {
        let mut line = String::from("    ");
        match (&o.long, o.short) {
            (Some(l), Some(c)) => {
                let _ = write!(line, "--{l}(-{c})");
            }
            (Some(l), None) => {
                let _ = write!(line, "--{l}");
            }
            (None, Some(c)) => {
                let _ = write!(line, "-{c}");
            }
            (None, None) => continue,
        }
        if o.takes_value {
            if o.possible.is_empty() {
                line.push_str(": string");
            } else {
                let _ = write!(line, ": string@{}", completer_name(node, o));
            }
        }
        if !o.help.is_empty() {
            let _ = write!(line, " # {}", o.help);
        }
        out.push_str(&line);
        out.push('\n');
    }
    if node.help_flag {
        out.push_str("    --help(-h) # Print help\n");
    }
    if node.version_flag {
        out.push_str("    --version(-V) # Print version\n");
    }
    out.push_str("  ]\n\n");
    for s in &node.subs {
        emit(out, s);
    }
}

fn completer_name(node: &Node, o: &crate::Opt) -> String {
    let name = o
        .long
        .clone()
        .or_else(|| o.short.map(|c| c.to_string()))
        .unwrap_or_default();
    format!("\"nu-complete {} {}\"", node.path.join(" "), name)
}

pub(crate) fn dynamic(bin: &str) -> String {
    let ident: String = bin
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    format!(
        "# dynamic nushell completion for {bin}, generated by hasami-complete\n\
def \"nu-complete {ident} dynamic\" [context: string] {{\n\
    let words = ($context | split row \" \")\n\
    with-env {{ _HASAMI_COMPLETE: \"nushell\", _HASAMI_COMPLETE_WORDS: ($words | str join (char -u 1f)), _HASAMI_COMPLETE_INDEX: (($words | length) - 1) }} {{\n\
        ^{bin} | lines | each {{ |l| let p = ($l | split row \"\\t\"); {{ value: $p.0, description: ($p | get -i 1 | default \"\") }} }}\n\
    }}\n\
}}\n\
export extern {q} [\n\
    ...args: string@\"nu-complete {ident} dynamic\"\n\
]\n",
        q = nq(bin),
    )
}
