use std::fmt::Write as _;

use crate::Node;

fn pq(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

pub(crate) fn generate(root: &Node) -> String {
    let bin = root.path.first().cloned().unwrap_or_default();
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# PowerShell completion for {bin}, generated by hasami-complete\nusing namespace System.Management.Automation\nusing namespace System.Management.Automation.Language\n"
    );
    let _ = writeln!(
        out,
        "Register-ArgumentCompleter -Native -CommandName {} -ScriptBlock {{",
        pq(&bin)
    );
    out.push_str("    param($wordToComplete, $commandAst, $cursorPosition)\n    $words = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })\n    $state = 'root'\n    for ($i = 1; $i -lt $words.Count; $i++) {\n        switch (\"$state,$($words[$i])\") {\n");
    emit_transitions(&mut out, root, "root");
    out.push_str("        }\n    }\n    $prev = if ($words.Count -gt 1) { $words[$words.Count - 1] } else { '' }\n    if ($wordToComplete -ne '' -and $prev -eq $wordToComplete) { $prev = if ($words.Count -gt 2) { $words[$words.Count - 2] } else { '' } }\n    $completions = @(switch (\"$state,$prev\") {\n");
    emit_values(&mut out, root, "root");
    out.push_str("        default { switch ($state) {\n");
    emit_words(&mut out, root, "root");
    out.push_str("        } }\n    })\n    $completions | Where-Object { $_.CompletionText -like \"$wordToComplete*\" } | Sort-Object -Property ListItemText\n}\n");
    out
}

fn tuple(text: &str, help: &str) -> String {
    format!(
        "[CompletionResult]::new({}, {}, [CompletionResultType]::ParameterName, {})",
        pq(text),
        pq(text),
        pq(if help.is_empty() { text } else { help })
    )
}

fn emit_transitions(out: &mut String, node: &Node, state: &str) {
    for s in &node.subs {
        let name = s.path.last().cloned().unwrap_or_default();
        let _ = writeln!(
            out,
            "            {} {{ $state = {} }}",
            pq(&format!("{state},{name}")),
            pq(&s.ident())
        );
        emit_transitions(out, s, &s.ident());
    }
}

fn emit_values(out: &mut String, node: &Node, state: &str) {
    for o in &node.opts {
        if !o.takes_value || o.possible.is_empty() {
            continue;
        }
        let mut names = Vec::new();
        if let Some(c) = o.short {
            names.push(format!("-{c}"));
        }
        if let Some(l) = &o.long {
            names.push(format!("--{l}"));
        }
        for n in names {
            let items: Vec<String> = o.possible.iter().map(|v| tuple(v, "")).collect();
            let _ = writeln!(
                out,
                "        {} {{ {} }}",
                pq(&format!("{state},{n}")),
                items.join("; ")
            );
        }
    }
    for s in &node.subs {
        emit_values(out, s, &s.ident());
    }
}

fn emit_words(out: &mut String, node: &Node, state: &str) {
    let mut items = Vec::new();
    for o in &node.opts {
        if let Some(c) = o.short {
            items.push(tuple(&format!("-{c}"), &o.help));
        }
        if let Some(l) = &o.long {
            items.push(tuple(&format!("--{l}"), &o.help));
        }
    }
    if node.help_flag {
        items.push(tuple("-h", "Print help"));
        items.push(tuple("--help", "Print help"));
    }
    if node.version_flag {
        items.push(tuple("-V", "Print version"));
        items.push(tuple("--version", "Print version"));
    }
    for s in &node.subs {
        items.push(tuple(
            s.path.last().map(String::as_str).unwrap_or(""),
            &s.about,
        ));
    }
    let _ = writeln!(out, "            {} {{ {} }}", pq(state), items.join("; "));
    for s in &node.subs {
        emit_words(out, s, &s.ident());
    }
}

pub(crate) fn dynamic(bin: &str) -> String {
    format!(
        "# dynamic PowerShell completion for {bin}, generated by hasami-complete\n\
Register-ArgumentCompleter -Native -CommandName {q} -ScriptBlock {{\n\
    param($wordToComplete, $commandAst, $cursorPosition)\n\
    $words = @($commandAst.CommandElements | ForEach-Object {{ $_.ToString() }})\n\
    if ($wordToComplete -eq '') {{ $words += '' }}\n\
    $env:_HASAMI_COMPLETE = 'powershell'\n\
    $env:_HASAMI_COMPLETE_WORDS = ($words -join [char]0x1f)\n\
    $env:_HASAMI_COMPLETE_INDEX = ($words.Count - 1)\n\
    try {{ & {q} | ForEach-Object {{ $p = $_ -split \"`t\", 2; [System.Management.Automation.CompletionResult]::new($p[0], $p[0], 'ParameterValue', $(if ($p.Count -gt 1) {{ $p[1] }} else {{ $p[0] }})) }} }}\n\
    finally {{ Remove-Item Env:_HASAMI_COMPLETE, Env:_HASAMI_COMPLETE_WORDS, Env:_HASAMI_COMPLETE_INDEX -ErrorAction SilentlyContinue }}\n\
}}\n",
        q = pq(bin),
    )
}
