[package]
name = "hasami-example-hexdump"
description = "A hex dumper written with #[derive(Args)]. Not published."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "hexdump"
path = "src/main.rs"

[dependencies]
hasami = { workspace = true, features = ["help", "derive"] }

[lints]
workspace = true
