[package]
name = "kanna-example-todo"
description = "A todo list manager written with the kanna cli! macro, with a REPL from kanna-prompt. Not published."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "todo"
path = "src/main.rs"

[dependencies]
kanna = { workspace = true, features = ["help", "suggest", "env"] }
kanna-complete = { path = "../../kanna-complete", version = "0.2.0" }
kanna-prompt = { path = "../../kanna-prompt", version = "0.2.0" }

[lints]
workspace = true
