[package]
name = "hasami-example-todo"
description = "A todo list manager written with the hasami cli! macro. Not published."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "todo"
path = "src/main.rs"

[dependencies]
hasami = { workspace = true, features = ["help", "suggest", "env"] }
hasami-complete = { path = "../../hasami-complete", version = "0.1.0" }

[lints]
workspace = true
