use std::fmt::Write as _;

use super::sq;
use crate::{Node, Opt};

pub(crate) fn generate(root: &Node) -> String {
    let bin = root.path.first().cloned().unwrap_or_default();
    let mut out = String::new();
    let _ = writeln!(
        out,
        "#compdef {bin}\n# zsh completion for {bin}, generated by kanna-complete"
    );
    emit_function(&mut out, root);
    let _ = writeln!(
        out,
        "\nif [ \"$funcstack[1]\" = \"_{}\" ]; then\n    _{} \"$@\"\nelse\n    compdef _{} {}\nfi",
        root.ident(),
        root.ident(),
        root.ident(),
        bin
    );
    out
}

fn zq(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('[', "\\[")
        .replace(']', "\\]")
        .replace(':', "\\:")
}

fn spec(o: &Opt) -> Vec<String> {
    let mut names = Vec::new();
    if let Some(c) = o.short {
        names.push(format!("-{c}"));
    }
    if let Some(l) = &o.long {
        names.push(format!("--{l}"));
    }
    for a in &o.aliases {
        names.push(format!("--{a}"));
    }
    let value = if o.takes_value {
        let action = if o.possible.is_empty() {
            "_files".to_owned()
        } else {
            format!("({})", o.possible.join(" "))
        };
        format!(":{}:{action}", zq(&o.value_name))
    } else {
        String::new()
    };
    let exclusion = if names.len() > 1 {
        format!("({})", names.join(" "))
    } else {
        String::new()
    };
    names
        .iter()
        .map(|n| sq(&format!("{exclusion}{n}[{}]{value}", zq(&o.help))))
        .collect()
}

fn emit_function(out: &mut String, node: &Node) {
    let _ = writeln!(
        out,
        "\n_{}() {{\n    local context state line\n    typeset -A opt_args\n    _arguments -s -S -C \\",
        node.ident()
    );
    for o in &node.opts {
        for s in spec(o) {
            let _ = writeln!(out, "        {s} \\");
        }
    }
    if node.help_flag {
        out.push_str("        '(-h --help)-h[Print help]' '(-h --help)--help[Print help]' \\\n");
    }
    if node.version_flag {
        out.push_str("        '(-V --version)-V[Print version]' '(-V --version)--version[Print version]' \\\n");
    }
    for (i, p) in node.positionals.iter().enumerate() {
        let action = if p.possible.is_empty() {
            "_files".to_owned()
        } else {
            format!("({})", p.possible.join(" "))
        };
        let _ = writeln!(out, "        '{}:{}:{action}' \\", i + 1, zq(&p.value_name));
    }
    if !node.subs.is_empty() {
        let _ = writeln!(
            out,
            "        ':command:->command' \\\n        '*::arg:->args' \\"
        );
    }
    out.push_str("        && return 0\n");
    if !node.subs.is_empty() {
        out.push_str("    case $state in\n        command)\n            local -a commands\n            commands=(\n");
        for s in &node.subs {
            let name = s.path.last().cloned().unwrap_or_default();
            let _ = writeln!(
                out,
                "                {}",
                sq(&format!("{name}:{}", zq(&s.about)))
            );
        }
        out.push_str("            )\n            _describe -t commands 'command' commands\n            ;;\n        args)\n            case $line[1] in\n");
        for s in &node.subs {
            let name = s.path.last().cloned().unwrap_or_default();
            let _ = writeln!(out, "                {name}) _{} ;;", s.ident());
        }
        out.push_str("            esac\n            ;;\n    esac\n");
    }
    out.push_str("}\n");
    for s in &node.subs {
        emit_function(out, s);
    }
}

pub(crate) fn dynamic(bin: &str) -> String {
    let ident: String = bin
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    format!(
        "#compdef {bin}\n# dynamic zsh completion for {bin}, generated by kanna-complete\n\
_{ident}_dynamic() {{\n\
    local -a completions\n\
    local IFS=$'\\n'\n\
    completions=(${{(f)\"$(_KANNA_COMPLETE=zsh _KANNA_COMPLETE_INDEX=\"$((CURRENT - 1))\" _KANNA_COMPLETE_WORDS=\"${{(pj:\\x1f:)words}}\" {bin})\"}})\n\
    _describe 'values' completions\n\
}}\n\
compdef _{ident}_dynamic {bin}\n",
    )
}
